""" "change_index"

Revision ID: ae85adbefd44
Revises: b5d82de57a0c
Create Date: 2025-07-13 14:13:14.872348

"""

import sqlalchemy as sa
from alembic import op

from db import postgres


# revision identifiers, used by Alembic.
revision = "ae85adbefd44"
down_revision = "b5d82de57a0c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "delivery_windows", ["id"])
    op.create_unique_constraint(None, "orders", ["id"])
    op.create_unique_constraint(None, "package_details", ["id"])
    op.drop_index(op.f("uq_parties_phone"), table_name="parties")
    op.create_index("uq_parties_unique", "parties", ["phone", "address", "first_name", "last_name"], unique=True)
    op.create_unique_constraint(None, "parties", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "parties", type_="unique")
    op.drop_index("uq_parties_unique", table_name="parties")
    op.create_index(op.f("uq_parties_phone"), "parties", ["phone"], unique=True)
    op.drop_constraint(None, "package_details", type_="unique")
    op.drop_constraint(None, "orders", type_="unique")
    op.drop_constraint(None, "delivery_windows", type_="unique")
    # ### end Alembic commands ###
