""""init"

Revision ID: b5d82de57a0c
Revises: 
Create Date: 2025-07-09 17:36:53.871794

"""
from alembic import op
import sqlalchemy as sa
from db import postgres


# revision identifiers, used by Alembic.
revision = 'b5d82de57a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parties',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('additional', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_parties_address', 'parties', ['address'], unique=False)
    op.create_index('ix_parties_company', 'parties', ['company'], unique=False)
    op.create_index('uq_parties_phone', 'parties', ['phone'], unique=True)
    op.create_table('orders',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'ASSIGNED', 'IN_PROGRESS', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('delivery_service_level', sa.Enum('STANDARD', 'EXPRESS', name='delivery_service_level'), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Enum('PREPAID', 'CASH_ON_DELIVERY', 'CARD_ON_DELIVERY', name='payment_method'), nullable=False),
    sa.Column('payment_status', sa.Boolean(), nullable=False),
    sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurance_number', sa.String(length=100), nullable=True),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.Column('additional', sa.Text(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('courier_id', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_photo_url', sa.String(length=500), nullable=True),
    sa.Column('recipient_signature', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_id'], ['parties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index('ix_orders_courier_id', 'orders', ['courier_id'], unique=False)
    op.create_table('delivery_windows',
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('time_from', sa.Time(), nullable=True),
    sa.Column('time_to', sa.Time(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('package_details',
    sa.Column('type', sa.Enum('BOX', 'PACKAGE', 'ENVELOPE', 'OTHER', name='package_type'), nullable=False),
    sa.Column('content_type', sa.Enum('LETTER', 'FOOD', 'GROCERY', 'ELECTRONICS', 'CLOTHING', 'OTHER', name='content_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('is_fragile', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package_details')
    op.drop_table('delivery_windows')
    op.drop_index('ix_orders_courier_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index('uq_parties_phone', table_name='parties')
    op.drop_index('ix_parties_company', table_name='parties')
    op.drop_index('ix_parties_address', table_name='parties')
    op.drop_table('parties')
    # ### end Alembic commands ###
