""""add_coordinates"

Revision ID: c6283b8448fd
Revises: 7e2a81bb3b30
Create Date: 2025-08-17 15:52:34.810113

"""
from alembic import op
import sqlalchemy as sa
from db import postgres


# revision identifiers, used by Alembic.
revision = 'c6283b8448fd'
down_revision = '7e2a81bb3b30'
branch_labels = None
depends_on = None


order_type = sa.Enum(
    "PICKUP", "DELIVERY", "SERVICE", name="order_type"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    order_type.create(bind, checkfirst=True)
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'package_details', ['id'])
    op.add_column('parties', sa.Column('lon', sa.Double(), nullable=False))
    op.add_column('parties', sa.Column('lat', sa.Double(), nullable=False))
    op.create_unique_constraint(None, 'parties', ['id'])
    op.create_unique_constraint(None, 'time_windows', ['id'])
    op.add_column('orders',
                  sa.Column('type', order_type, nullable=False, server_default=sa.text("'DELIVERY'::order_type")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    op.drop_column("orders", "type")
    op.drop_column('orders', 'type')
    op.drop_constraint(None, 'time_windows', type_='unique')
    op.drop_constraint(None, 'parties', type_='unique')
    op.drop_column('parties', 'lat')
    op.drop_column('parties', 'lon')
    op.drop_constraint(None, 'package_details', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')

    order_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
