""""init orders table"

Revision ID: d758c639905c
Revises:
Create Date: 2024-01-15 12:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from db import postgres  # noqa


# revision identifiers, used by Alembic.
revision = "d758c639905c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("recipient_phone", sa.String(length=20), nullable=False),
        sa.Column("recipient_email", sa.String(length=255), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=False),
        sa.Column("delivery_latitude", sa.String(length=20), nullable=True),
        sa.Column("delivery_longitude", sa.String(length=20), nullable=True),
        sa.Column("delivery_date", sa.DateTime(), nullable=True),
        sa.Column("delivery_time_from", sa.DateTime(), nullable=True),
        sa.Column("delivery_time_to", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("courier_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("delivery_photo_url", sa.String(length=500), nullable=True),
        sa.Column("recipient_signature", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("order_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    # ### end Alembic commands ###
