""""split orders table into multiple tables"

Revision ID: split_orders_table
Revises: d758c639905c
Create Date: 2024-01-15 14:00:00.000000

"""
import sqlalchemy as sa
from alembic import op
from db import postgres  # noqa


# revision identifiers, used by Alembic.
revision = "split_orders_table"
down_revision = "d758c639905c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create package_details table
    op.create_table(
        "package_details",
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("content_type", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("length", sa.Float(), nullable=True),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("is_fragile", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    
    # Create parties table
    op.create_table(
        "parties",
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("additional", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    
    # Create delivery_windows table
    op.create_table(
        "delivery_windows",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time_from", sa.Time(), nullable=True),
        sa.Column("time_to", sa.Time(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    
    # Create payments table
    op.create_table(
        "payments",
        sa.Column("method", sa.String(length=20), nullable=False),
        sa.Column("sum", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    
    # Drop the old orders table
    op.drop_table("orders")
    
    # Create new orders table with relationships
    op.create_table(
        "orders",
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("delivery_service_level", sa.String(length=20), nullable=False),
        sa.Column("tracking_id", sa.UUID(), nullable=False),
        sa.Column("insurance_number", sa.String(length=100), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("additional", sa.Text(), nullable=True),
        sa.Column("package_details_id", sa.UUID(), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=True),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("delivery_window_id", sa.UUID(), nullable=True),
        sa.Column("payment_id", sa.UUID(), nullable=True),
        sa.Column("courier_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("delivery_photo_url", sa.String(length=500), nullable=True),
        sa.Column("recipient_signature", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["package_details_id"], ["package_details.id"]),
        sa.ForeignKeyConstraint(["sender_id"], ["parties.id"]),
        sa.ForeignKeyConstraint(["recipient_id"], ["parties.id"]),
        sa.ForeignKeyConstraint(["delivery_window_id"], ["delivery_windows.id"]),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("tracking_id"),
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new orders table
    op.drop_table("orders")
    
    # Drop new tables
    op.drop_table("payments")
    op.drop_table("delivery_windows")
    op.drop_table("parties")
    op.drop_table("package_details")
    
    # Recreate old orders table
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=False),
        sa.Column("recipient_phone", sa.String(length=20), nullable=False),
        sa.Column("recipient_email", sa.String(length=255), nullable=True),
        sa.Column("delivery_address", sa.Text(), nullable=False),
        sa.Column("delivery_latitude", sa.String(length=20), nullable=True),
        sa.Column("delivery_longitude", sa.String(length=20), nullable=True),
        sa.Column("delivery_date", sa.DateTime(), nullable=True),
        sa.Column("delivery_time_from", sa.DateTime(), nullable=True),
        sa.Column("delivery_time_to", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("special_instructions", sa.Text(), nullable=True),
        sa.Column("courier_id", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("delivery_photo_url", sa.String(length=500), nullable=True),
        sa.Column("recipient_signature", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("order_number"),
    )
    
    # ### end Alembic commands ###